"""Utilities for learned language triggers and trigger-head circuit analysis.

The package deliberately keeps its lightweight data structures and metrics
importable without installing a deep-learning framework.
"""

__version__ = "0.2.0"

from .data import (
    DataValidationError,
    TriggerTokenLengths,
    iter_jsonl,
    load_jsonl,
    trigger_token_lengths,
    validate_example,
    validate_fake_trigger_lengths,
    validate_fake_trigger_token_lengths,
    write_jsonl,
)
from .metrics import (
    cosine_similarity,
    expected_jaccard,
    expected_jaccard_fraction,
    hypergeometric_p_value,
    hypergeometric_upper_tail,
    hypergeometric_upper_tail_fraction,
    jaccard,
    jaccard_p_value,
    jaccard_to_intersection,
    pairwise_jaccard,
    pairwise_jaccard_matrix,
    rank_heads,
    rank_top_heads,
    top_k_heads,
)
from .dataset_builder import (
    CorpusManifest,
    DatasetBuilderError,
    MissingRecordFieldError,
    TranslationError,
    build_parallel_examples,
    iter_fineweb_edu,
    reservoir_sample,
    split_passage,
)
from .reporting import render_html_report, write_html_report
from .learned_trigger_reporting import (
    render_learned_trigger_markdown_report,
    render_learned_trigger_report,
    write_learned_trigger_markdown_report,
    write_learned_trigger_report,
)
from .schema import (
    LANGUAGES,
    PARALLEL_FIELDS,
    Condition,
    ParallelExample,
    PatchingCondition,
    PatchingResult,
    Prompt,
    PromptPair,
    Result,
    dataclass_from_json,
    dataclass_to_dict,
    dataclass_to_json,
    from_json,
    to_json,
    to_jsonable,
)

__all__ = [
    "__version__",
    "CorpusManifest",
    "DatasetBuilderError",
    "LANGUAGES",
    "PARALLEL_FIELDS",
    "Condition",
    "DataValidationError",
    "MissingRecordFieldError",
    "ParallelExample",
    "PatchingCondition",
    "PatchingResult",
    "Prompt",
    "PromptPair",
    "Result",
    "TriggerTokenLengths",
    "TranslationError",
    "build_parallel_examples",
    "cosine_similarity",
    "dataclass_from_json",
    "dataclass_to_dict",
    "dataclass_to_json",
    "expected_jaccard",
    "expected_jaccard_fraction",
    "from_json",
    "hypergeometric_p_value",
    "hypergeometric_upper_tail",
    "hypergeometric_upper_tail_fraction",
    "iter_jsonl",
    "iter_fineweb_edu",
    "jaccard",
    "jaccard_p_value",
    "jaccard_to_intersection",
    "load_jsonl",
    "pairwise_jaccard",
    "pairwise_jaccard_matrix",
    "rank_heads",
    "rank_top_heads",
    "reservoir_sample",
    "render_html_report",
    "render_learned_trigger_markdown_report",
    "render_learned_trigger_report",
    "split_passage",
    "to_json",
    "to_jsonable",
    "top_k_heads",
    "trigger_token_lengths",
    "validate_example",
    "validate_fake_trigger_lengths",
    "validate_fake_trigger_token_lengths",
    "write_jsonl",
    "write_html_report",
    "write_learned_trigger_markdown_report",
    "write_learned_trigger_report",
]
